 # Generated by Django 6.0.7 on 2026-07-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrollement_date',
        ),
    ]
