# Generated by Django 6.0.7 on 2026-07-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_student_enrollement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
    ]
